#ifndef _VISUAL_T_H_
#define _VISUAL_T_H_

enum visual_t {POINT=1, LINE, FILL, CHECKERED, ILUM_PLANO, ILUM_SOFT};
enum light_t {DIRECTIONAL=0, POSITIONAL};
enum selected_t {BODY_T=1, HEAD_R, TRASH_DOOR_R, SHOULDER_LEFT_R, ELBOW_LEFT_R, LOWER_LEFT_FINGER_R, UPPER_LEFT_FINGER_R, SHOULDER_RIGHT_R, ELBOW_RIGHT_R, LOWER_RIGHT_FINGER_R, UPPER_RIGHT_FINGER_R, BODY_R};
#endif